/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPagamentoRouteImport } from './routes/_authenticated/pagamento'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDinheiroRouteImport } from './routes/_authenticated/app.dinheiro'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppJornadaRouteImport } from './routes/_authenticated/app.jornada'
import { Route as AuthenticatedAppManutencaoRouteImport } from './routes/_authenticated/app.manutencao'
import { Route as AuthenticatedAppMetasRouteImport } from './routes/_authenticated/app.metas'
import { Route as AuthenticatedAppMotoRouteImport } from './routes/_authenticated/app.moto'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'
import { Route as AuthenticatedAppMotoIndexRouteImport } from './routes/_authenticated/app.moto.index'
import { Route as AuthenticatedAppMotoAbastecimentosRouteImport } from './routes/_authenticated/app.moto.abastecimentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentoRoute = AuthenticatedPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDinheiroRoute =
  AuthenticatedAppDinheiroRouteImport.update({
    id: '/dinheiro',
    path: '/dinheiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJornadaRoute = AuthenticatedAppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppManutencaoRoute =
  AuthenticatedAppManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMetasRoute = AuthenticatedAppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMotoRoute = AuthenticatedAppMotoRouteImport.update({
  id: '/moto',
  path: '/moto',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppMotoIndexRoute =
  AuthenticatedAppMotoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppMotoRoute,
  } as any)
const AuthenticatedAppMotoAbastecimentosRoute =
  AuthenticatedAppMotoAbastecimentosRouteImport.update({
    id: '/abastecimentos',
    path: '/abastecimentos',
    getParentRoute: () => AuthenticatedAppMotoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/moto': typeof AuthenticatedAppMotoRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
  '/app/moto/': typeof AuthenticatedAppMotoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
  '/app/moto': typeof AuthenticatedAppMotoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pagamento': typeof AuthenticatedPagamentoRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/_authenticated/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/_authenticated/app/metas': typeof AuthenticatedAppMetasRoute
  '/_authenticated/app/moto': typeof AuthenticatedAppMotoRouteWithChildren
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
  '/_authenticated/app/moto/': typeof AuthenticatedAppMotoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/auth/callback'
    | '/auth/'
    | '/app/dinheiro'
    | '/app/documentos'
    | '/app/jornada'
    | '/app/manutencao'
    | '/app/metas'
    | '/app/moto'
    | '/app/perfil'
    | '/app/relatorios'
    | '/api/public/cakto-webhook'
    | '/app/'
    | '/app/moto/abastecimentos'
    | '/app/moto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/auth/callback'
    | '/auth'
    | '/app/dinheiro'
    | '/app/documentos'
    | '/app/jornada'
    | '/app/manutencao'
    | '/app/metas'
    | '/app/perfil'
    | '/app/relatorios'
    | '/api/public/cakto-webhook'
    | '/app'
    | '/app/moto/abastecimentos'
    | '/app/moto'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/pagamento'
    | '/_authenticated/planos'
    | '/auth/callback'
    | '/auth/'
    | '/_authenticated/app/dinheiro'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/jornada'
    | '/_authenticated/app/manutencao'
    | '/_authenticated/app/metas'
    | '/_authenticated/app/moto'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/relatorios'
    | '/api/public/cakto-webhook'
    | '/_authenticated/app/'
    | '/_authenticated/app/moto/abastecimentos'
    | '/_authenticated/app/moto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamento': {
      id: '/_authenticated/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthenticatedPagamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dinheiro': {
      id: '/_authenticated/app/dinheiro'
      path: '/dinheiro'
      fullPath: '/app/dinheiro'
      preLoaderRoute: typeof AuthenticatedAppDinheiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jornada': {
      id: '/_authenticated/app/jornada'
      path: '/jornada'
      fullPath: '/app/jornada'
      preLoaderRoute: typeof AuthenticatedAppJornadaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/manutencao': {
      id: '/_authenticated/app/manutencao'
      path: '/manutencao'
      fullPath: '/app/manutencao'
      preLoaderRoute: typeof AuthenticatedAppManutencaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/metas': {
      id: '/_authenticated/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AuthenticatedAppMetasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moto': {
      id: '/_authenticated/app/moto'
      path: '/moto'
      fullPath: '/app/moto'
      preLoaderRoute: typeof AuthenticatedAppMotoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/moto/': {
      id: '/_authenticated/app/moto/'
      path: '/'
      fullPath: '/app/moto/'
      preLoaderRoute: typeof AuthenticatedAppMotoIndexRouteImport
      parentRoute: typeof AuthenticatedAppMotoRoute
    }
    '/_authenticated/app/moto/abastecimentos': {
      id: '/_authenticated/app/moto/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/app/moto/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAppMotoAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedAppMotoRoute
    }
  }
}

interface AuthenticatedAppMotoRouteChildren {
  AuthenticatedAppMotoAbastecimentosRoute: typeof AuthenticatedAppMotoAbastecimentosRoute
  AuthenticatedAppMotoIndexRoute: typeof AuthenticatedAppMotoIndexRoute
}

const AuthenticatedAppMotoRouteChildren: AuthenticatedAppMotoRouteChildren = {
  AuthenticatedAppMotoAbastecimentosRoute:
    AuthenticatedAppMotoAbastecimentosRoute,
  AuthenticatedAppMotoIndexRoute: AuthenticatedAppMotoIndexRoute,
}

const AuthenticatedAppMotoRouteWithChildren =
  AuthenticatedAppMotoRoute._addFileChildren(AuthenticatedAppMotoRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDinheiroRoute: typeof AuthenticatedAppDinheiroRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppJornadaRoute: typeof AuthenticatedAppJornadaRoute
  AuthenticatedAppManutencaoRoute: typeof AuthenticatedAppManutencaoRoute
  AuthenticatedAppMetasRoute: typeof AuthenticatedAppMetasRoute
  AuthenticatedAppMotoRoute: typeof AuthenticatedAppMotoRouteWithChildren
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDinheiroRoute: AuthenticatedAppDinheiroRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppJornadaRoute: AuthenticatedAppJornadaRoute,
  AuthenticatedAppManutencaoRoute: AuthenticatedAppManutencaoRoute,
  AuthenticatedAppMetasRoute: AuthenticatedAppMetasRoute,
  AuthenticatedAppMotoRoute: AuthenticatedAppMotoRouteWithChildren,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPagamentoRoute: typeof AuthenticatedPagamentoRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPagamentoRoute: AuthenticatedPagamentoRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
