/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDinheiroRouteImport } from './routes/_authenticated/app.dinheiro'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppJornadaRouteImport } from './routes/_authenticated/app.jornada'
import { Route as AuthenticatedAppManutencaoRouteImport } from './routes/_authenticated/app.manutencao'
import { Route as AuthenticatedAppMetasRouteImport } from './routes/_authenticated/app.metas'
import { Route as AuthenticatedAppMotoRouteImport } from './routes/_authenticated/app.moto'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppMotoAbastecimentosRouteImport } from './routes/_authenticated/app.moto.abastecimentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDinheiroRoute =
  AuthenticatedAppDinheiroRouteImport.update({
    id: '/dinheiro',
    path: '/dinheiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJornadaRoute = AuthenticatedAppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppManutencaoRoute =
  AuthenticatedAppManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMetasRoute = AuthenticatedAppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMotoRoute = AuthenticatedAppMotoRouteImport.update({
  id: '/moto',
  path: '/moto',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMotoAbastecimentosRoute =
  AuthenticatedAppMotoAbastecimentosRouteImport.update({
    id: '/abastecimentos',
    path: '/abastecimentos',
    getParentRoute: () => AuthenticatedAppMotoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/moto': typeof AuthenticatedAppMotoRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/moto': typeof AuthenticatedAppMotoRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/dinheiro': typeof AuthenticatedAppDinheiroRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/jornada': typeof AuthenticatedAppJornadaRoute
  '/_authenticated/app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/_authenticated/app/metas': typeof AuthenticatedAppMetasRoute
  '/_authenticated/app/moto': typeof AuthenticatedAppMotoRouteWithChildren
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/moto/abastecimentos': typeof AuthenticatedAppMotoAbastecimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/app/dinheiro'
    | '/app/documentos'
    | '/app/jornada'
    | '/app/manutencao'
    | '/app/metas'
    | '/app/moto'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/'
    | '/app/moto/abastecimentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/app/dinheiro'
    | '/app/documentos'
    | '/app/jornada'
    | '/app/manutencao'
    | '/app/metas'
    | '/app/moto'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app'
    | '/app/moto/abastecimentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/dinheiro'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/jornada'
    | '/_authenticated/app/manutencao'
    | '/_authenticated/app/metas'
    | '/_authenticated/app/moto'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/'
    | '/_authenticated/app/moto/abastecimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dinheiro': {
      id: '/_authenticated/app/dinheiro'
      path: '/dinheiro'
      fullPath: '/app/dinheiro'
      preLoaderRoute: typeof AuthenticatedAppDinheiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jornada': {
      id: '/_authenticated/app/jornada'
      path: '/jornada'
      fullPath: '/app/jornada'
      preLoaderRoute: typeof AuthenticatedAppJornadaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/manutencao': {
      id: '/_authenticated/app/manutencao'
      path: '/manutencao'
      fullPath: '/app/manutencao'
      preLoaderRoute: typeof AuthenticatedAppManutencaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/metas': {
      id: '/_authenticated/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AuthenticatedAppMetasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moto': {
      id: '/_authenticated/app/moto'
      path: '/moto'
      fullPath: '/app/moto'
      preLoaderRoute: typeof AuthenticatedAppMotoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moto/abastecimentos': {
      id: '/_authenticated/app/moto/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/app/moto/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAppMotoAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedAppMotoRoute
    }
  }
}

interface AuthenticatedAppMotoRouteChildren {
  AuthenticatedAppMotoAbastecimentosRoute: typeof AuthenticatedAppMotoAbastecimentosRoute
}

const AuthenticatedAppMotoRouteChildren: AuthenticatedAppMotoRouteChildren = {
  AuthenticatedAppMotoAbastecimentosRoute:
    AuthenticatedAppMotoAbastecimentosRoute,
}

const AuthenticatedAppMotoRouteWithChildren =
  AuthenticatedAppMotoRoute._addFileChildren(AuthenticatedAppMotoRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDinheiroRoute: typeof AuthenticatedAppDinheiroRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppJornadaRoute: typeof AuthenticatedAppJornadaRoute
  AuthenticatedAppManutencaoRoute: typeof AuthenticatedAppManutencaoRoute
  AuthenticatedAppMetasRoute: typeof AuthenticatedAppMetasRoute
  AuthenticatedAppMotoRoute: typeof AuthenticatedAppMotoRouteWithChildren
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDinheiroRoute: AuthenticatedAppDinheiroRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppJornadaRoute: AuthenticatedAppJornadaRoute,
  AuthenticatedAppManutencaoRoute: AuthenticatedAppManutencaoRoute,
  AuthenticatedAppMetasRoute: AuthenticatedAppMetasRoute,
  AuthenticatedAppMotoRoute: AuthenticatedAppMotoRouteWithChildren,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
